# Generated by Django 2.2.2 on 2021-04-03 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_auto_20210403_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='imei',
        ),
    ]
