# Generated by Django 3.2 on 2021-05-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fromESP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='espAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numID', models.PositiveIntegerField()),
                ('bid', models.PositiveSmallIntegerField()),
                ('rid', models.PositiveSmallIntegerField()),
                ('weekDay', models.PositiveSmallIntegerField()),
                ('timeSlot', models.TimeField(null=True)),
                ('ping', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='timeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.PositiveSmallIntegerField()),
                ('rid', models.PositiveSmallIntegerField()),
                ('slotA', models.TimeField(null=True)),
                ('slotB', models.TimeField(null=True)),
                ('slotC', models.TimeField(null=True)),
                ('slotD', models.TimeField(null=True)),
                ('slotE', models.TimeField(null=True)),
                ('slotF', models.TimeField(null=True)),
                ('slotG', models.TimeField(null=True)),
                ('slotH', models.TimeField(null=True)),
                ('slotI', models.TimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='espdata',
            name='datetime',
        ),
        migrations.AddField(
            model_name='espdata',
            name='dayStamp',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='espdata',
            name='timeStamp',
            field=models.TimeField(auto_now=True),
        ),
    ]
