# Generated by Django 3.2 on 2021-05-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fromESP', '0002_auto_20210523_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espdata',
            name='dayStamp',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='espdata',
            name='timeStamp',
            field=models.TimeField(),
        ),
    ]
