# Generated by Django 3.2 on 2021-05-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fromESP', '0003_auto_20210523_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='deltaA',
            field=models.PositiveSmallIntegerField(default=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='deltaB',
            field=models.PositiveSmallIntegerField(default=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='deltaC',
            field=models.PositiveSmallIntegerField(default=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='deltaD',
            field=models.PositiveSmallIntegerField(default=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='deltaE',
            field=models.PositiveSmallIntegerField(default=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='deltaF',
            field=models.PositiveSmallIntegerField(default=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='deltaG',
            field=models.PositiveSmallIntegerField(default=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='deltaH',
            field=models.PositiveSmallIntegerField(default=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeslot',
            name='deltaI',
            field=models.PositiveSmallIntegerField(default=90),
            preserve_default=False,
        ),
    ]
