# Generated by Django 3.1.7 on 2021-06-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fromESP', '0006_auto_20210612_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='testData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('timeScan', models.FloatField()),
                ('bid', models.PositiveSmallIntegerField()),
                ('rid', models.PositiveSmallIntegerField()),
                ('numID', models.PositiveIntegerField()),
                ('rssi', models.SmallIntegerField()),
            ],
        ),
    ]
