# Generated by Django 3.1.7 on 2021-05-30 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='espAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayStamp', models.DateField(auto_now_add=True)),
                ('numID', models.PositiveIntegerField()),
                ('bid', models.PositiveSmallIntegerField()),
                ('rid', models.PositiveSmallIntegerField()),
                ('weekDay', models.PositiveSmallIntegerField()),
                ('timeSlot', models.TimeField(null=True)),
                ('ping', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='espData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayStamp', models.DateField()),
                ('timeStamp', models.TimeField()),
                ('bid', models.PositiveSmallIntegerField()),
                ('rid', models.PositiveSmallIntegerField()),
                ('numID', models.PositiveIntegerField()),
                ('rssi', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='timeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.PositiveSmallIntegerField()),
                ('rid', models.PositiveSmallIntegerField()),
                ('slotA', models.TimeField(null=True)),
                ('slotB', models.TimeField(null=True)),
                ('slotC', models.TimeField(null=True)),
                ('slotD', models.TimeField(null=True)),
                ('slotE', models.TimeField(null=True)),
                ('slotF', models.TimeField(null=True)),
                ('slotG', models.TimeField(null=True)),
                ('slotH', models.TimeField(null=True)),
                ('slotI', models.TimeField(null=True)),
                ('deltaA', models.PositiveSmallIntegerField()),
                ('deltaB', models.PositiveSmallIntegerField()),
                ('deltaC', models.PositiveSmallIntegerField()),
                ('deltaD', models.PositiveSmallIntegerField()),
                ('deltaE', models.PositiveSmallIntegerField()),
                ('deltaF', models.PositiveSmallIntegerField()),
                ('deltaG', models.PositiveSmallIntegerField()),
                ('deltaH', models.PositiveSmallIntegerField()),
                ('deltaI', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
