# Generated by Django 3.1.7 on 2021-05-30 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_espdata_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='espdata',
            name='course',
        ),
    ]
