# Generated by Django 3.1.7 on 2021-05-30 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_remove_espdata_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='espdata',
            name='course',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='info.course'),
        ),
    ]
