# Generated by Django 3.1.7 on 2021-05-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_espdata_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espdata',
            name='course',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
