# Generated by Django 3.1.7 on 2021-06-12 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_espdatadaily_daystamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Mapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.PositiveSmallIntegerField()),
                ('building_id', models.PositiveSmallIntegerField()),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='info.course')),
            ],
        ),
    ]
